apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: sharmarajdaksh/gittix/expiration:latest
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: "nats://nats-clusterip:4222"
            - name: NATS_CLUSTER_ID
              value: gittix
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: "expiration-redis-clusterip"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
