name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - "ordering/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd auth && docker build -t sharmarajdaksh/gittix/expiration .
      - run: docker push sharmarajdaksh/gittix/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes-cluster kubeconfig save gittix-cluster
      - run: kubectl rollout restart deployment ordering-deployment
