name: run-orders-tests

on:
  pull_request:
    paths:
      - "ordering/**"

jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ordering && npm install && npm run test:ci
