name: run-payments-tests

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
