name: run-tickets-tests

on:
  pull_request:
    paths:
      - "ticketing/**"

jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing && npm install && npm run test:ci
